CREATE TABLE [dbo].[Class]
(
	[Id] UNIQUEIDENTIFIER CONSTRAINT [DF_Class_ID] DEFAULT NEWSEQUENTIALID() NOT NULL, 
    [Name] VARCHAR(255) NOT NULL, 
    [Description] VARCHAR(255) NULL, 
    [StartTime] DATETIMEOFFSET NOT NULL, 
    [EndTime] DATETIMEOFFSET NOT NULL, 
    [Deadline] DATETIMEOFFSET NOT NULL, 
    [AvailableSpots] TINYINT NOT NULL, 
    [IsAvailableForAll] BIT CONSTRAINT [DF_Class_IsAvailableForAll] DEFAULT 1 NOT NULL, 
    [RecordCreatedAt] DATETIMEOFFSET CONSTRAINT [DF_Class_RecordCreatedAt] DEFAULT SYSDATETIMEOFFSET() NOT NULL, 
    [RecordUpdatedAt] DATETIMEOFFSET NULL, 
    [ClubID] UNIQUEIDENTIFIER NOT NULL, 
    [ClassTypeID] UNIQUEIDENTIFIER NOT NULL, 
    [CancellationID] UNIQUEIDENTIFIER NULL, 
    [ClusterID] INT NOT NULL IDENTITY,
    CONSTRAINT [PK_Class] PRIMARY KEY NonCLUSTERED ([Id] ASC)
);
GO

CREATE UNIQUE CLUSTERED INDEX [IX_Class_ClusterID] ON [dbo].[Class] ([ClusterID])
GO
